### PR TITLE
Upgrade dev dependencies to the latest version

### PR DESCRIPTION
**Pull request by stof**

### CODE REVIEW

**Comment by stof** [comment]
Changes done in 2nd to 6th commits are about fixing errors reporting by the new analyzer rules.

**Comment by nex3** [comment]
Can we disable the string composition lint? I think that's pretty universally making the code look worse.

**Comment by stof** [comment]
@nex3 updated with the lint rule disabled. I also updated the `sass-analysis` dependency to use lints 2.0 for consistency.

**Comment by nex3** [comment]
What happened to the two disables you removed from the analysis config?

**Comment by stof** [comment]
@nex3 as explained in the commit message removing them, those rules were part of the pedantic config but are not part of the `lints` recommended config. So they were ignoring rule that were not enabled in the first place.

**Review by nex3 — APPROVED** [review]

**Comment by nex3** [comment]
Thanks!

**Pull request merged**
