### PR TITLE
Add built-in modules for core Sass functions

### PR DESCRIPTION
**Pull request by nex3**
Partially addresses #554

See https://github.com/sass/sass-spec/pull/1400

### CODE REVIEW

**Comment by nex3** [comment]
It might be a good idea to look at the color file; that module has the most differences between the module-system version and the global-function version, which means the most changes from the old structure.

**Comment by nshahan** [comment]
Thanks I'll give a closer look now.

**Comment by nshahan** [comment]
To confirm, should I expect that the functions in this chart that do not appear in the global module should be removed in this change?
https://github.com/sass/sass/blob/master/accepted/module-system.md#built-in-modules-1

For example, should `red`, `green`, `blue` be removed from the global module and only available in color?

**Comment by nex3** [comment]
No, everything that was available globally is still available globally, for backwards compatibility. The functions that are listed as global in that chart are ones that are intended to *always* remain in the global namespace.

**Comment by nex3** [comment]
Thanks Nick!

**Pull request merged**
