### PR TITLE
Deprecated mixed declarations

### PR DESCRIPTION
**Pull request by nex3**
See sass/sass#3885
See https://github.com/sass/sass-spec/pull/2002

### CODE REVIEW

**Review by jathak — APPROVED** [review]
This needs a changelog entry and the sass_api major version should be bumped.

**Review by jathak — APPROVED** [review]

**Comment by nex3** [comment]
Dartdoc seems to be failing due to https://github.com/dart-lang/dartdoc/issues/3818

**Comment by stefanv** [comment]
Confusingly, the page linked to in the warning gives an example that, due CSS specificity rules, renders the same under old and new behaviors. Do we have examples of where new behavior creates differences?

**Comment by nex3** [comment]
Yes, any example where the nested rule doesn't affect specificity:

```scss
.example {
  color: red;

  @media screen {
    font-weight: bold;
  }

  font-weight: normal;
}
```

**Pull request merged**
