### PR TITLE
Add support for css empty namespace attribute selector

### PR DESCRIPTION
**Pull request by pjeweb**
sass/sass-spec#1742

Fixes: sass/sass#3199

### CODE REVIEW

**Comment by stof** [comment]
Please add a reference to the sass-spec PR in your PR description, so that the CI runs the patched sass-spec (once the workflow run is approved by a maintainer)

**Comment by stof** [comment]
the change looks good to me

**Comment by pjeweb** [comment]
I think the CI did not actually test with the new spec. I think it may be either because of a newline before the link or just because i changed the pr message afterwards. Maybe someone can trigger a new run? Thanks!

**Review by nex3 — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
