### PR TITLE
fixes for the windows archives

### PR DESCRIPTION
**Pull request by m4r71n**

### CODE REVIEW

**Comment by nex3** [comment]
Please run `pub run grinder format` to reformat the Dart change.

**Comment by m4r71n** [comment]
Ah Thx. I wondered why the travis build failed but now I've seen the exact reason

**Comment by nex3** [comment]
Make sure to sign the CLA as well!

**Comment by m4r71n** [comment]
I signed it!

**Comment by nex3** [comment]
Thanks for the patch!

**Pull request merged**
