### PR TITLE
Run Travis on OS X.

### PR DESCRIPTION
**Pull request by nex3**

### CODE REVIEW

**Comment by nschonni** [comment]
Is there a reason to split out the `spec` and `test` runs?

**Comment by nex3** [comment]
I generally like having different builds for different types of tests. Also, we'd need a way to run only tests anyway, since we don't want to run specs for each version of Node.

**Comment by nschonni** [comment]
Fair enough, I was just thinking about the slowdown from waiting for the separate builds to start might outweigh that. Especially since the OSX infrastructure seems to get congested regularly

**Comment by nschonni** [comment]
You could also noop the specific run parts on the Node stuff like we do for the coverage in libsass

**Comment by nex3** [comment]
We're doing that somewhat via the build matrix. It may be worth just running everything in a single job on OS X though for that reason.

**Comment by nschonni** [comment]
Maybe move that to a `ci-travis` script? I think my thinking was the same as yours done from a differnt angle, I just remember problems with trying to get the matrix to behave in the past.

**Comment by nex3** [comment]
I'm going to close this out for now. The cycle time of OS X builds is too high to realistically make it part of our continuous integration system. We'll have to figure something else out if we want to build releases on OS X, unfortunately.

**Pull request closed without merging**
