### PR TITLE
Update node_preamble, hopefully fixing electron support

### PR DESCRIPTION
**Pull request by Mstrodl**
See mrbullington/node_preamble.dart#20 for more information

### CODE REVIEW

**Comment by Mstrodl** [comment]
@googlebot I signed it!

**Comment by Awjin** [comment]
Thanks for looking into this. The current dependency `^1.1.0` already supports all versions of `node_preamble` up to the next major release, so you can update your packages to get `1.4.9`.

**Comment by Mstrodl** [comment]
@Awjin I believe dart-sass will need to be published with a new version to npm in that case to be compiled with the new node_preamble then?

**Comment by Awjin** [comment]
The latest dart-sass release (1.26.6) should support this

**Comment by Mstrodl** [comment]
@Awjin Is that going to be published to npm or?

**Comment by Awjin** [comment]
Every release is automatically published to npm. https://www.npmjs.com/package/sass

**Comment by Mstrodl** [comment]
@Awjin My bad, I was looking at the [https://www.npmjs.com/package/dart-sass](https://www.npmjs.com/package/dart-sass) package

**Pull request closed without merging**
